import daisyui from 'daisyui'
import forms from '@tailwindcss/forms'

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono', 'ui-monospace', 'monospace'],
      },
      colors: {
        canvas: 'hsl(var(--b1) / <alpha-value>)',
        surface: 'hsl(var(--b2, var(--b1)) / <alpha-value>)',
        accent: 'hsl(var(--a) / <alpha-value>)',
        ink: 'hsl(var(--bc) / <alpha-value>)',
        steel: 'hsl(var(--bc) / 0.65)',
        whisper: 'hsl(var(--bc) / 0.18)',
      },
      boxShadow: {
        diffused: '0 4px 24px rgba(0, 0, 0, 0.4)',
      },
    },
  },
  plugins: [daisyui, forms],
  daisyui: {
    themes: [
      {
        light: {
          "color-scheme": "light",
          "primary": "#2563eb",
          "secondary": "#8b5cf6",
          "accent": "#4f46e5",
          "neutral": "#f1f5f9",
          "base-100": "#ffffff",
          "base-200": "#f8fafc",
          "base-300": "#e2e8f0",
          "base-content": "#0f172a",
          "info": "#0ea5e9",
          "success": "#22c55e",
          "warning": "#f59e0b",
          "error": "#ef4444",
        },
        dark: {
          "color-scheme": "dark",
          "primary": "#3b82f6",
          "secondary": "#d946ef",
          "accent": "#8b5cf6",
          "neutral": "#1e293b",
          "base-100": "#0f172a",
          "base-200": "#1e293b",
          "base-300": "#334155",
          "base-content": "#f8fafc",
          "info": "#0ea5e9",
          "success": "#22c55e",
          "warning": "#f59e0b",
          "error": "#ef4444",
        },
        black: {
          "color-scheme": "dark",
          "primary": "#f8fafc",
          "secondary": "#d946ef",
          "accent": "#0ea5e9",
          "neutral": "#27272a",
          "base-100": "#000000",
          "base-200": "#09090b",
          "base-300": "#18181b",
          "base-content": "#ffffff",
          "info": "#3b82f6",
          "success": "#10b981",
          "warning": "#f59e0b",
          "error": "#ef4444",
        },
        cupcake: {
          "color-scheme": "light",
          "primary": "#65c3c8",
          "secondary": "#ef9fbc",
          "accent": "#D4A373", 
          "neutral": "#291334",
          "base-100": "#faf7f5",
          "base-200": "#efeae6",
          "base-300": "#e7e2df",
          "base-content": "#291334",
          "info": "#7dd3fc",
          "success": "#34d399",
          "warning": "#f5a524",
          "error": "#f87171",
        },
        dracula: {
          "color-scheme": "dark",
          "primary": "#ff79c6",
          "secondary": "#bd93f9",
          "accent": "#ffb86c",
          "neutral": "#414558",
          "base-100": "#282a36",
          "base-200": "#21222c",
          "base-300": "#191a21",
          "base-content": "#f8f8f2",
          "info": "#8be9fd",
          "success": "#50fa7b",
          "warning": "#f1fa8c",
          "error": "#ff5555",
        },
        // cspell:disable-next-line
        synthwave: {
          "color-scheme": "dark",
          "primary": "#e779c1",
          "secondary": "#58c7f3",
          "accent": "#f3cc30",
          "neutral": "#20134e",
          "base-100": "#2d1b69",
          "base-200": "#20134e",
          "base-300": "#140a32",
          "base-content": "#f9f7fd",
          "info": "#53c0f9",
          "success": "#71ead2",
          "warning": "#e3d664",
          "error": "#ff6f6f",
        }
      }
    ],
  },
}
